In [1]:
import numpy as np

1. Create a numpy array with values from 0 to 10 in steps of 0.5


In [2]:
test_array = np.arange(0, 10, 0.5)

2. Extract the the last three elements of the array (without manually setting the array length).

In [6]:
len_array = test_array.shape[0]
len_array

20

In [7]:
test_array[len_array-3::]

array([8.5, 9. , 9.5])

3. Apply a cosine function to the array and store the output in a new array.


In [8]:
cos_array = np.cos(test_array)

4. Create a boolean array telling which values in the array from (2) are smaller than 0.

In [9]:
sel_array = cos_array < 0
sel_array

array([False, False, False, False,  True,  True,  True,  True,  True,
        True, False, False, False, False, False, False,  True,  True,
        True,  True])

5. Recover only those values in a new array via indexing.

In [10]:
values = cos_array[sel_array]
values

array([-0.41614684, -0.80114362, -0.9899925 , -0.93645669, -0.65364362,
       -0.2107958 , -0.14550003, -0.6020119 , -0.91113026, -0.99717216])